# Библиотека NumPy

Содержит константы, функции и объекты для работы с многомерными массивами данных. Используется в анализе данных, машинном обучении, научных вычислениях.

In [ ]:
import numpy as np

## Создание массивов

Основным объектом NumPy является многомерный массив (numpy.ndarray). Это n-мерный массив из элементов (обычно чисел) одного типа - вектор, матрица, тензор и т.д. Используются для представления табличных данных, изображений, текста, звука.

### Одномерные массивы

Функция `array()` трансформирует последовательность в многомерный массив.

In [ ]:
a = np.array([1, 2, 3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
a = ['AAA', 1, 2, 3, 4, 5]
print(np.array(a))

['AAA' '1' '2' '3' '4' '5']


Функция `arange()`, аналогичная встроенной в Python `range()`, возвращает массив.

In [ ]:
a = np.arange(2, 20, 3) # создание массива в диапазоне [2, 20) с шагом 3
print(a)

[ 2  5  8 11 14 17]


Функция `linspace(start, stop, num)` создает массив размером `num` элементов из чисел в диапазоне от `start` до `stop` с равным промежутком.

In [ ]:
print(np.linspace(100, 1000, 10))

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]


Функция `logspace(start, stop, num, base=10)` создает массив размером `num` элементов из чисел в диапазоне от `base ** start` до `base ** stop` с равным промежутком.

In [ ]:
print(np.logspace(3., 10., 10))

[1.00000000e+03 5.99484250e+03 3.59381366e+04 2.15443469e+05
 1.29154967e+06 7.74263683e+06 4.64158883e+07 2.78255940e+08
 1.66810054e+09 1.00000000e+10]


In [ ]:
a.ndim # размерность массива (количество осей)

1

In [ ]:
a.shape # размер массива (форма) - количество строк, столбцов и т.д.

(6,)

In [ ]:
a.size # количество элементов массива

6

### Двумерные массивы

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a.ndim

2

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

Функция `zeros()` создает массив из нулей, функция `ones()` — массив из единиц. Функция `eye()` создаёт единичную матрицу. Эти функции принимают кортеж с размерами, и аргумент dtype.

In [ ]:
zeros = np.zeros((2, 3), dtype=np.int32)
ones = np.ones((5, 10), dtype=np.float64)
identity = np.eye(3)

print(zeros, end='\n\n')
print(ones, end='\n\n')
print(identity)

[[0 0 0]
 [0 0 0]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.diag(identity)) # выводит диагональ матрицы

[1. 1. 1.]


In [ ]:
print(np.diag([1,2,3])) # создает матрицу с заданной диагональю

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Изменение формы массива

Для для изменения формы любого массива без изменения данных, которые в нем находятся, используется функция `reshape()`.

In [ ]:
a1 = np.arange(24)
print(a1.ndim)
print(a1)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
a2 = np.arange(24).reshape(12, 2)
print(a2.ndim)
print(a2)

2
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [ ]:
a3 = np.arange(24).reshape(3, 2, 4)
print(a3.ndim)
print(a3)

3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a = np.arange(24).reshape(-1, 8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


Функция `flatten()` возвращает одномерный массив.

In [ ]:
print(a.flatten()) # копия

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
a.ndim

2

Транспонирование матриц.

In [ ]:
print(a2, end='\n\n')
print(a2.T) # транспонирование возвращает копию

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[ 0  2  4  6  8 10 12 14 16 18 20 22]
 [ 1  3  5  7  9 11 13 15 17 19 21 23]]


## Индексация и срезы

Одномерные массивы похожи на простые списки Python. Обратиться к элементу можно по его индексу.

In [ ]:
a = np.arange(10)
a[2]

2

Обращение к элементам и извлечение срезов в многомерных массивах производится не по одному, а по нескольким индексам (каждый индекс соответствует своей оси).

In [ ]:
print(a2)
print('Отдельные элементы: ', a2[0, 0], a2[1, 1], a2[-1, -1])

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Отдельные элементы:  0 3 23


Можно создать маску индексов и по маске вытащить нужные элементы.

In [ ]:
evens = np.array([x for x in range(10) if x % 2 == 0])
print(evens) # маска индексов
letters = np.array(list('abcdefghij'))
print(letters)
print(letters[evens])

[0 2 4 6 8]
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
['a' 'c' 'e' 'g' 'i']


In [ ]:
indexes = np.array([True] * 5 + [False] * 5)
print(indexes) # маска индексов
print(letters[indexes])

[ True  True  True  True  True False False False False False]
['a' 'b' 'c' 'd' 'e']


In [ ]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
print(a2[:3, :]) #  cрез из строк и столбцов

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b = a2[5:, 1:]
print(b)

[[11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]]


In [ ]:
b[2, 0]

15

In [ ]:
b[2, 0] *= 100
print(b)

[[  11]
 [  13]
 [1500]
 [  17]
 [  19]
 [  21]
 [  23]]


In [ ]:
print(a2)

[[   0    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]
 [  10   11]
 [  12   13]
 [  14 1500]
 [  16   17]
 [  18   19]
 [  20   21]
 [  22   23]]


In [ ]:
b2 = a2         # не создаем новый массив
print(a2 is b2) # это две ссылки на один и тот же массив
c2 = a2.copy()  # создаем копию массива
print(a2 is c2) # теперь это разные массивы

True
False


## Соединение массивов

In [ ]:
a = np.zeros(9, dtype=int).reshape(3, 3)
b = np.ones(9, dtype=int).reshape(3, 3)

ab1 = np.hstack((a, b))
ab2 = np.vstack((a, b))

print('a:\n', a)
print('b:\n', b)
print('Horizontal Stack:\n', ab1)
print('Vertical Stack:\n', ab2)

a:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
b:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Horizontal Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Vertical Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a = np.ones(16).reshape(2, -1)

a_1, a_2 = np.vsplit(a, 2) # разделяем вертикально на 2 массива
# a_1, a_2 = np.hsplit(a, 2)

print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1.]]



In [ ]:
print(np.r_[0:10, 4:8, 100]) # горизонтальное соединение - в строку

[  0   1   2   3   4   5   6   7   8   9   4   5   6   7 100]


In [ ]:
print(np.c_[1:3, 7:9, 0:2]) # вертикальное соединение - в столбцы

[[1 7 0]
 [2 8 1]]


In [ ]:
a = np.arange(1, 10)
print(np.split(a, [5])) # разделение массива по элементу
print(np.split(a, [4, 6]))

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]
[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


## Сортировка массивов

In [ ]:
a = np.array([[1,4],[3,1]])
print(a, end='\n\n')
print(np.sort(a, axis=None), end='\n\n')  # сортировка одномерного массива
print(np.sort(a, axis=0), end='\n\n')     # сортировка по столбцам
print(np.sort(a, axis=1), end='\n\n')     # сортировка по строкам

[[1 4]
 [3 1]]

[1 1 3 4]

[[1 1]
 [3 4]]

[[1 4]
 [1 3]]



## Математические операции

Математические операции над массивами выполняются поэлементно. Создается новый массив, который заполняется результатами действия оператора.

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[        inf 30.         20.         16.66666667]
[     1     30   1600 125000]


<ipython-input-36-ea07be89d1e0>:6: RuntimeWarning: divide by zero encountered in divide
  print(a / b)


Массивы должны быть одинаковых размеров.

In [ ]:
a = np.arange(9)
b = np.arange(1)
print(a + b)

[0 1 2 3 4 5 6 7 8]


Математические операции между массивом и числом.

In [ ]:
print(a + 100)
print(a ** 2)
print(a > 5)

[100 101 102 103 104 105 106 107 108]
[ 0  1  4  9 16 25 36 49 64]
[False False False False False False  True  True  True]


NumPy также предоставляет множество математических операций для обработки массивов.

In [ ]:
print(np.sin(a))
print(np.exp(a))
print(np.log1p(a))
print(np.sqrt(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712]


## Агрегирование массивов

Многие унарные операции, такие как `np.sum()`, представлены также и в виде методов класса `ndarray`.

In [ ]:
print(np.sum(a))
print(a.sum())

36
36


По умолчанию эти операции применяются к массиву целиком, независимо от его формы. Однако, указав параметр `axis`, можно применить операцию для указанной оси массива.

In [ ]:
a = a.reshape(3, -1)
print(a)
print('Min по столбцам:\n', a.min(axis=0))
print('Min по строкам:\n', a.min(axis=1))
print('Min по матрице:\n', a.min())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Min по столбцам:
 [0 1 2]
Min по строкам:
 [0 3 6]
Min по матрице:
 0


In [ ]:
print(a.max(axis=1))  # максимальные значения по строкам
print(a.sum(axis=1))  # сумма по строкам
print(a.prod(axis=1)) # произведение по строкам
print(a.mean(axis=1)) # среднее значение по строкам

[2 5 8]
[ 3 12 21]
[  0  60 336]
[1. 4. 7.]


Функции `argmax()` и `argmin()` возвращают индексы максимальных или минимальных элементов по осям.

In [ ]:
print(a.argmax(axis=0))
print(a.argmax(axis=1))

[2 2 2]
[2 2 2]


## Линейная алгебра
Модуль библиотеки `numpy.linalg` позволяет выполнять многие операции из линейной алгебры.

In [ ]:
a = np.arange(1, 5).reshape(2, 2)
print(a)
np.linalg.det(a).round() # определитель матрицы

[[1 2]
 [3 4]]


-2.0

### Умножение матриц
Умножать можно только матрицы, отвечающие следующему требованию: количество столбцов первой матрицы должно быть равно числу строк второй матрицы.

In [ ]:
a = np.arange(1, 9).reshape(2, 4)
b = np.arange(8, 0, -1).reshape(4, 2)
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[8 7]
 [6 5]
 [4 3]
 [2 1]]


In [ ]:
c = np.dot(a, b) # скалярное произведение матриц
print(c)

[[ 40  30]
 [120  94]]


In [ ]:
a @ b

array([[ 40,  30],
       [120,  94]])

### Обратная матрица

In [ ]:
c_inv = np.linalg.inv(c)
print(c_inv)

[[ 0.5875 -0.1875]
 [-0.75    0.25  ]]


In [ ]:
print(np.round(np.dot(c, c_inv)))

[[ 1. -0.]
 [-0.  1.]]


## Генерация случайных чисел в numpy
Для создания массивов со случайными элементами служит модуль `numpy.random`.

In [ ]:
np.random.seed(1000) # инициализация генератора псевдослучайных чисел

Функция `sample()` возвращает числа из промежутка `[0, 1)` в виде константы, вектора или матрицы.

In [ ]:
np.random.seed(1000)
print(np.random.sample(10))

[0.65358959 0.11500694 0.95028286 0.4821914  0.87247454 0.21233268
 0.04070962 0.39719446 0.2331322  0.84174072]


In [ ]:
print(np.random.sample((2, 3)))

[[0.76568299 0.55408724 0.88509294]
 [0.90419762 0.0104217  0.07455674]]


Функция `randint(low, high, size)` создает массив из целых чисел. Параметры `low, high, size`: от какого, до какого числа, размер массива.

In [ ]:
print(np.random.randint(0, 5, 10))

[1 1 4 1 4 0 2 1 0 4]


Функция `uniform(low, high, size)` создает массив из вещественных чисел, используя равномерное распределение. Параметры `low, high, size`: от какого, до какого числа, размер массива.

In [ ]:
print(np.random.uniform(0, 5, (3, 3)))

[[1.01747217 2.68755912 1.18471502]
 [2.1824608  3.99012257 1.54204582]
 [3.10758314 2.19824059 4.56661853]]


Функция `rand(d1, d2, d3, ...)` получает требуемый размер массива и заполняет его числами, которые случайно распределены в интервале от 0 до 1.

In [ ]:
print(np.random.rand(3, 3, 3))

[[[0.24462921 0.13330475 0.6979251 ]
  [0.39820488 0.88312219 0.18100751]
  [0.43249917 0.0181432  0.69143786]]

 [[0.46969065 0.12822219 0.89133705]
  [0.91820362 0.07312099 0.04544794]
  [0.4385729  0.60172093 0.31022703]]

 [[0.68190824 0.20901315 0.5196043 ]
  [0.56598883 0.44116739 0.13755616]
  [0.21354319 0.13337189 0.3222967 ]]]


Функция `randn(d1, d2, d3, ...)` создает массив указанной формы и заполняет его случайными числами с плавающей точкой, которые выбраны из одномерного нормального распределения со средним значением равным 0 и дисперсией равной 1.

In [ ]:
print(np.random.randn(3, 5))

[[-2.20641858  0.17689153  0.35002301  1.36126025  0.65295373]
 [ 0.34968236 -0.4264542   0.31940268  1.73734602 -2.70792836]
 [-2.004896    1.31406313 -0.22436882 -0.21499877 -0.1107533 ]]


Перемешать массив можно с помощью функций `shuffle()` или `permutation()`.

In [ ]:
a = np.arange(10)
np.random.shuffle(a)
print(a)

[5 9 2 6 4 3 7 8 1 0]


In [ ]:
print(np.random.permutation(a)) # создает копию

[2 6 3 8 9 5 1 0 7 4]


In [ ]:
print(a)

[5 9 2 6 4 3 7 8 1 0]


Сделать случайную выборку из массива можно с помощью функции `choice()`.

In [ ]:
print(np.random.choice(a, 10, replace=True))

[3 5 9 9 7 0 3 9 9 1]


## Ссылки

[Numpy](https://numpy.org/doc/stable/reference/arrays.html)

## Задания

1. Создайте вектор `a` со значениями от 5 до 50 включительно. Числа из вектора `a`, которые делятся на 5 без остатка запишите в вектор `b`.  Выведите `b` на экран. Циклы не используем (1 балл)

In [ ]:
import numpy as np
# код

2. Создайте вектор из 12 элементов. Изменяйте его форму каждый раз так, чтобы получилось шесть разных двумерных массивов и три трехмерных. Выведите все новые массивы на экран. Они должны быть разной формы и состоять из всех элементов исходного вектора  (2 балла)

In [ ]:
# код

3. Создайте матрицу размером 5х5 с нулями. На главной диагонале поставьте числа 1, 2, 3, 4, 5. Эти же числа должны располагаться в первой строчке и первом столбце. Циклы не используем  (1 балл)

In [ ]:
# код

4. Создайте матрицу размером 7х7 с нулями. На двух диагоналях поставьте единицы. Единицы должны располагаться в крайних строчках и крайних столбцах. Циклы не используем  (1 балл)

In [ ]:
# код

5. Соедините вертикально два двумерных массива. Первый массив состоит из нулей, число его строк на единицу больше, чем строк во втором массиве. Второй массив состоит из единиц. Результирующий массив должен иметь атрибут `size`, равный 15 (2 балла)

In [ ]:
# код

6. Создайте матрицу, у которой первый столбец содержит числа 1, 4, 6, 9, а второй столбец: 3, 5, 1, 7. Найдите средние значения каждого столбца и отнимите от каждого элемента столбца свое среднее значение. Скалярно умножьте два столбца матрицы. В ответе должно получиться 12. Циклы не используем (2 балла)

In [ ]:
# код

7. Создайте матрицу 5 х 5, которая состоит из нормально распределенных чисел. Поменяйте местами крайние столбики без использования дополнительной переменной.  Циклы не используем (1 балл)

In [ ]:
# код

## Сравнение времени выполнения кода

In [1]:
def sum_for(array1, array2):
  sum = 0
  for el1, el2 in zip(array1, array2):
    sum += el1 + el2
  return sum

n = 1000000
lst1 = [i for i in range(n)]
lst2 = [i for i in range(n)][::-1]
%timeit sum_for(lst1, lst2)

113 ms ± 47.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
import numpy as np

def sum_numpy(array1, array2):
  return np.sum(array1 + array2)

arr1 = np.array(lst1)
arr2 = np.array(lst2)
%timeit sum_numpy(arr1, arr2)

4.42 ms ± 381 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
